name: nbconvert_docs
channels:
  - conda-forge
  - default
dependencies:
- python>=3.5
- pandoc
- nbformat
- jupyter_client
- ipython
- sphinx
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
    - nbsphinx
