name: nbconvert_docs
channels:
  - conda-forge
  - defaults
dependencies:
- python=3.5
- pandoc
- nbformat
- jupyter_client
- ipython
- sphinx!=1.5
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
   - pip>=9.0
   - setuptools
   - docutils<0.13.1
   - git+https://github.com/spatialaudio/nbsphinx.git#egg=nbsphinx
